-- Rename turn_id to trace_id in memory_turns and memory_signals.
--
-- Each row in memory_turns corresponds to one completed request — a full agent
-- loop — not to an individual model step within that loop. The runtime engine
-- identifies the loop with trace_id (generated by start_request_trace()), so
-- the column name in the store should match.
--
-- Postgres automatically updates the FK on memory_signals when the referenced
-- column in memory_turns is renamed, so constraint surgery is not required.

ALTER TABLE memory_turns RENAME COLUMN turn_id TO trace_id;
ALTER TABLE memory_signals RENAME COLUMN turn_id TO trace_id;
