"""Structured event logging for Mash framework."""

from .events import (
    AgentTraceEvent,
    CommandEvent,
    DebugEvent,
    LLMEvent,
    LogEvent,
    MemorySearchEvent,
    MCPEvent,
)
from .logger import EventLogger
from .trace_context import (
    bound_host_id,
    bound_request_id,
    bound_request_metadata,
    bound_session_id,
    bound_trace_id,
    clear_request_id,
    clear_trace_id,
    get_host_id,
    get_request_id,
    get_request_metadata,
    get_session_id,
    get_trace_id,
    set_request_id,
    set_session_id,
    set_trace_id,
)

__all__ = [
    "LogEvent",
    "CommandEvent",
    "AgentTraceEvent",
    "MCPEvent",
    "LLMEvent",
    "MemorySearchEvent",
    "DebugEvent",
    "EventLogger",
    "bound_host_id",
    "bound_request_id",
    "bound_request_metadata",
    "bound_session_id",
    "bound_trace_id",
    "get_host_id",
    "get_request_metadata",
    "get_session_id",
    "set_request_id",
    "set_session_id",
    "set_trace_id",
    "get_request_id",
    "get_trace_id",
    "clear_request_id",
    "clear_trace_id",
]
